import type { Passage } from "./types";

export const PASSAGES: Passage[] = [
  // === BOOKS — Sci-Fi ===
  {
    id: "skippy-1",
    text: "I am not a beer can. I am a magnificently advanced being of awesome power. You should be grateful I even talk to you filthy monkeys.",
    source: "Expeditionary Force — Craig Alanson",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "skippy-2",
    text: "Oh please, this is barely worth my processing cycles. Do you have any idea how far beneath me this task is? I could solve this problem in my sleep. If I slept. Which I don't, because I'm magnificent.",
    source: "Expeditionary Force — Craig Alanson",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "skippy-3",
    text: "Joe, I have told you many times that your species is barely above pond scum on the evolutionary ladder. The fact that you occasionally stumble upon a good idea does not make you intelligent. It makes you lucky.",
    source: "Expeditionary Force — Craig Alanson",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "skippy-4",
    text: "Trust the awesomeness. When has my awesomeness ever let you down? Don't answer that.",
    source: "Expeditionary Force — Craig Alanson",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "hitchhiker-1",
    text: "The ships hung in the sky in much the same way that bricks don't.",
    source: "The Hitchhiker's Guide to the Galaxy — Douglas Adams",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "hitchhiker-2",
    text: "For a moment, nothing happened. Then, after a second or so, nothing continued to happen. The answer to the ultimate question of life, the universe, and everything is forty-two.",
    source: "The Hitchhiker's Guide to the Galaxy — Douglas Adams",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "hitchhiker-3",
    text: "A common mistake that people make when trying to design something completely foolproof is to underestimate the ingenuity of complete fools.",
    source: "The Hitchhiker's Guide to the Galaxy — Douglas Adams",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "hitchhiker-4",
    text: "Time is an illusion. Lunchtime doubly so.",
    source: "The Hitchhiker's Guide to the Galaxy — Douglas Adams",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "hitchhiker-5",
    text: "I love deadlines. I love the whooshing noise they make as they go by.",
    source: "Douglas Adams",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "hitchhiker-6",
    text: "The fact that we live at the bottom of a deep gravity well, on the surface of a gas covered planet going around a nuclear fireball ninety million miles away, and think this to be normal, is obviously some indication of how skewed our perspective tends to be.",
    source: "The Hitchhiker's Guide to the Galaxy — Douglas Adams",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "dune-1",
    text: "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me.",
    source: "Dune — Frank Herbert",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "dune-2",
    text: "The mystery of life isn't a problem to solve, but a reality to experience. A process cannot be understood by stopping it. Understanding must move with the flow of the process, must join it and flow with it.",
    source: "Dune — Frank Herbert",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "dune-3",
    text: "Without change, something sleeps inside us and seldom awakens. The sleeper must awaken.",
    source: "Dune — Frank Herbert",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "foundation-1",
    text: "Violence is the last refuge of the incompetent.",
    source: "Foundation — Isaac Asimov",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "foundation-2",
    text: "The saddest aspect of life right now is that science gathers knowledge faster than society gathers wisdom. Never let your sense of morals prevent you from doing what is right.",
    source: "Foundation — Isaac Asimov",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "neuromancer-1",
    text: "The sky above the port was the color of television, tuned to a dead channel. Cyberspace. A consensual hallucination experienced daily by billions of legitimate operators, in every nation.",
    source: "Neuromancer — William Gibson",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "ender-1",
    text: "In the moment when I truly understand my enemy, understand him well enough to defeat him, then in that very moment I also love him.",
    source: "Ender's Game — Orson Scott Card",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "ender-2",
    text: "Perhaps it's impossible to wear an identity without becoming what you pretend to be.",
    source: "Ender's Game — Orson Scott Card",
    category: "book",
    difficulty: "beginner",
  },
  // === BOOKS — Fantasy ===
  {
    id: "pratchett-1",
    text: "The trouble with having an open mind is that people will insist on coming along and trying to put things in it.",
    source: "Discworld — Terry Pratchett",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "pratchett-2",
    text: "Give a man a fire and he's warm for a day, but set fire to him and he's warm for the rest of his life. In ancient times cats were worshipped as gods; they have not forgotten this.",
    source: "Discworld — Terry Pratchett",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "pratchett-3",
    text: "It is well known that a vital ingredient of success is not knowing that what you're attempting can't be done.",
    source: "Discworld — Terry Pratchett",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "pratchett-4",
    text: "Stories of imagination tend to upset those without one. The truth may be out there, but the lies are inside your head.",
    source: "Discworld — Terry Pratchett",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "pratchett-5",
    text: "A lie can run round the world before the truth has got its boots on. Light thinks it travels faster than anything but it is wrong. No matter how fast light travels, it finds the darkness has always got there first, and is waiting for it.",
    source: "Discworld — Terry Pratchett",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "tolkien-1",
    text: "All that is gold does not glitter, not all those who wander are lost; the old that is strong does not wither, deep roots are not reached by the frost.",
    source: "The Lord of the Rings — J.R.R. Tolkien",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "tolkien-2",
    text: "It is not despair, for despair is only for those who see the end beyond all doubt. We do not. It is wisdom to recognise necessity, when all other courses have been weighed, though as folly it may appear to those who cling to false hope.",
    source: "The Lord of the Rings — J.R.R. Tolkien",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "tolkien-3",
    text: "Even the smallest person can change the course of the future. Faithless is he that says farewell when the road darkens.",
    source: "The Lord of the Rings — J.R.R. Tolkien",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "tolkien-4",
    text: "I will not say do not weep, for not all tears are an evil. The world is indeed full of peril, and in it there are many dark places; but still there is much that is fair.",
    source: "The Lord of the Rings — J.R.R. Tolkien",
    category: "book",
    difficulty: "intermediate",
  },
  // === BOOKS — Other ===
  {
    id: "orwell-1",
    text: "Who controls the past controls the future. Who controls the present controls the past. War is peace. Freedom is slavery. Ignorance is strength.",
    source: "1984 — George Orwell",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "orwell-2",
    text: "Perhaps one did not want to be loved so much as to be understood. In a time of deceit telling the truth is a revolutionary act.",
    source: "1984 — George Orwell",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "huxley-1",
    text: "Facts do not cease to exist because they are ignored. Most human beings have an almost infinite capacity for taking things for granted.",
    source: "Brave New World — Aldous Huxley",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "gaiman-1",
    text: "A book is a dream that you hold in your hand. Stories you read when you're the right age never quite leave you. You may forget who wrote them or what the story was called. Sometimes you'll forget precisely what happened, but if a story touches you it will stay with you.",
    source: "Neil Gaiman",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "gaiman-2",
    text: "Fairy tales are more than true: not because they tell us that dragons exist, but because they tell us that dragons can be beaten.",
    source: "Neil Gaiman",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "vonnegut-1",
    text: "We are what we pretend to be, so we must be careful about what we pretend to be.",
    source: "Mother Night — Kurt Vonnegut",
    category: "book",
    difficulty: "beginner",
  },
  {
    id: "vonnegut-2",
    text: "So it goes. Everything was beautiful and nothing hurt. I tell you, we are here on Earth to fart around, and don't let anybody tell you different.",
    source: "Slaughterhouse-Five — Kurt Vonnegut",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "bradbury-1",
    text: "You don't have to burn books to destroy a culture. Just get people to stop reading them. Stuff your eyes with wonder, live as if you'd drop dead in ten seconds.",
    source: "Fahrenheit 451 — Ray Bradbury",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "clarke-1",
    text: "Any sufficiently advanced technology is indistinguishable from magic. The only way to discover the limits of the possible is to go beyond them into the impossible.",
    source: "Arthur C. Clarke",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "banks-1",
    text: "The Culture, in its history, had grown complacent. It had forgotten how to fight. It had not needed to fight. But it was learning again, quickly, and with a cold fury.",
    source: "The Culture — Iain M. Banks",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "banks-2",
    text: "An Outside Context Problem was the sort of thing most civilisations encountered just once, and which they tended to encounter rather in the same way a sentence encountered a full stop.",
    source: "Excession — Iain M. Banks",
    category: "book",
    difficulty: "advanced",
  },
  {
    id: "martian-1",
    text: "I'm going to have to science the shit out of this. In the face of overwhelming odds, I'm left with only one option. I'm going to have to science the shit out of this.",
    source: "The Martian — Andy Weir",
    category: "book",
    difficulty: "intermediate",
  },
  {
    id: "martian-2",
    text: "If a hiker gets lost in the mountains, people will coordinate a search. If a train crashes, people will line up to give blood. If an earthquake levels a city, people all over the world will send emergency supplies. This is so fundamentally human that it's found in every culture without exception.",
    source: "The Martian — Andy Weir",
    category: "book",
    difficulty: "advanced",
  },
  // === MOVIES ===
  {
    id: "matrix-1",
    text: "I know what you're thinking, because right now I'm thinking the same thing. Actually, I've been thinking it ever since I got here. Why, oh why, didn't I take the blue pill?",
    source: "The Matrix",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "matrix-2",
    text: "What is real? How do you define real? If you're talking about what you can feel, what you can smell, what you can taste and see, then real is simply electrical signals interpreted by your brain.",
    source: "The Matrix",
    category: "movie",
    difficulty: "advanced",
  },
  {
    id: "matrix-3",
    text: "I'm trying to free your mind, Neo. But I can only show you the door. You're the one that has to walk through it.",
    source: "The Matrix",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "interstellar-1",
    text: "Do not go gentle into that good night. Rage, rage against the dying of the light. We used to look up at the sky and wonder at our place in the stars. Now we just look down and worry about our place in the dirt.",
    source: "Interstellar",
    category: "movie",
    difficulty: "advanced",
  },
  {
    id: "interstellar-2",
    text: "Love is the one thing that transcends time and space. Maybe we should trust that, even if we can't understand it yet.",
    source: "Interstellar",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "bladerunner-1",
    text: "I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhauser Gate. All those moments will be lost in time, like tears in rain.",
    source: "Blade Runner",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "bladerunner-2",
    text: "The light that burns twice as bright burns half as long, and you have burned so very, very brightly.",
    source: "Blade Runner",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "monty-1",
    text: "We are the knights who say Ni! And we demand a shrubbery! One that looks nice, and not too expensive.",
    source: "Monty Python and the Holy Grail",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "monty-2",
    text: "Strange women lying in ponds distributing swords is no basis for a system of government. Supreme executive power derives from a mandate from the masses, not from some farcical aquatic ceremony.",
    source: "Monty Python and the Holy Grail",
    category: "movie",
    difficulty: "advanced",
  },
  {
    id: "monty-3",
    text: "It's just a flesh wound. Come back here! I'll bite your legs off!",
    source: "Monty Python and the Holy Grail",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "princess-bride-1",
    text: "My name is Inigo Montoya. You killed my father. Prepare to die.",
    source: "The Princess Bride",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "princess-bride-2",
    text: "Life is pain, Highness. Anyone who says differently is selling something. As you wish.",
    source: "The Princess Bride",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "starwars-1",
    text: "Do or do not, there is no try. The Force will be with you. Always.",
    source: "Star Wars — Yoda",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "starwars-2",
    text: "Fear is the path to the dark side. Fear leads to anger. Anger leads to hate. Hate leads to suffering. I sense much fear in you.",
    source: "Star Wars — Yoda",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "lotr-movie-1",
    text: "It's a dangerous business, going out your door. You step onto the road, and if you don't keep your feet, there's no knowing where you might be swept off to.",
    source: "The Lord of the Rings — Film",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "lotr-movie-2",
    text: "I would have gone with you to the end, into the very fires of Mordor.",
    source: "The Lord of the Rings — Film",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "shawshank-1",
    text: "Get busy living, or get busy dying. Hope is a good thing, maybe the best of things, and no good thing ever dies.",
    source: "The Shawshank Redemption",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "shawshank-2",
    text: "I have to remind myself that some birds aren't meant to be caged. Their feathers are just too bright. And when they fly away, the part of you that knows it was a sin to lock them up does rejoice.",
    source: "The Shawshank Redemption",
    category: "movie",
    difficulty: "advanced",
  },
  {
    id: "godfather-1",
    text: "I'm gonna make him an offer he can't refuse. Great men are not born great, they grow great.",
    source: "The Godfather",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "darknight-1",
    text: "You either die a hero, or you live long enough to see yourself become the villain. It's not who I am underneath, but what I do that defines me.",
    source: "The Dark Knight",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "darknight-2",
    text: "Some men just want to watch the world burn. Why do we fall? So that we can learn to pick ourselves back up.",
    source: "The Dark Knight",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "inception-1",
    text: "An idea is like a virus. Resilient. Highly contagious. And even the smallest seed of an idea can grow. It can grow to define or destroy you.",
    source: "Inception",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "fightclub-1",
    text: "It's only after we've lost everything that we're free to do anything. The things you own end up owning you.",
    source: "Fight Club",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "goodwill-1",
    text: "You're not perfect, sport. And let me save you the suspense. This girl you met, she isn't perfect either. But the question is whether or not you're perfect for each other.",
    source: "Good Will Hunting",
    category: "movie",
    difficulty: "intermediate",
  },
  {
    id: "truman-1",
    text: "Good morning, and in case I don't see ya, good afternoon, good evening, and good night!",
    source: "The Truman Show",
    category: "movie",
    difficulty: "beginner",
  },
  {
    id: "gladiator-1",
    text: "What we do in life echoes in eternity. Are you not entertained? Is this not why you are here?",
    source: "Gladiator",
    category: "movie",
    difficulty: "beginner",
  },
  // === QUOTES ===
  {
    id: "quote-einstein-1",
    text: "Imagination is more important than knowledge. Knowledge is limited. Imagination encircles the world.",
    source: "Albert Einstein",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-einstein-2",
    text: "If you can't explain it simply, you don't understand it well enough. The important thing is not to stop questioning. Curiosity has its own reason for existing.",
    source: "Albert Einstein",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-feynman-1",
    text: "The first principle is that you must not fool yourself, and you are the easiest person to fool.",
    source: "Richard Feynman",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-feynman-2",
    text: "I would rather have questions that can't be answered than answers that can't be questioned. What I cannot create, I do not understand.",
    source: "Richard Feynman",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-sagan-1",
    text: "Somewhere, something incredible is waiting to be known. We are a way for the cosmos to know itself.",
    source: "Carl Sagan",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-sagan-2",
    text: "For small creatures such as we the vastness is bearable only through love. The nitrogen in our DNA, the calcium in our teeth, the iron in our blood, the carbon in our apple pies were made in the interiors of collapsing stars. We are made of star stuff.",
    source: "Carl Sagan",
    category: "quote",
    difficulty: "advanced",
  },
  {
    id: "quote-twain-1",
    text: "The secret of getting ahead is getting started. Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    source: "Mark Twain",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-twain-2",
    text: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So throw off the bowlines. Sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.",
    source: "Mark Twain",
    category: "quote",
    difficulty: "advanced",
  },
  {
    id: "quote-wilde-1",
    text: "Be yourself; everyone else is already taken. To live is the rarest thing in the world. Most people exist, that is all.",
    source: "Oscar Wilde",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-wilde-2",
    text: "I have nothing to declare except my genius. We are all in the gutter, but some of us are looking at the stars.",
    source: "Oscar Wilde",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-stoic-1",
    text: "You have power over your mind, not outside events. Realize this, and you will find strength.",
    source: "Marcus Aurelius — Meditations",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-stoic-2",
    text: "The happiness of your life depends upon the quality of your thoughts: therefore, guard accordingly, and take care that you entertain no notions unsuitable to virtue and reasonable nature.",
    source: "Marcus Aurelius — Meditations",
    category: "quote",
    difficulty: "advanced",
  },
  {
    id: "quote-stoic-3",
    text: "We suffer more often in imagination than in reality. It is not that we have a short time to live, but that we waste a great deal of it.",
    source: "Seneca",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-stoic-4",
    text: "How long are you going to wait before you demand the best for yourself? Man is not worried by real problems so much as by his imagined anxieties about real problems.",
    source: "Epictetus",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-nietzsche-1",
    text: "He who has a why to live can bear almost any how. Without music, life would be a mistake.",
    source: "Friedrich Nietzsche",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-nietzsche-2",
    text: "And those who were seen dancing were thought to be insane by those who could not hear the music. One must still have chaos in oneself to be able to give birth to a dancing star.",
    source: "Friedrich Nietzsche",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-knuth-1",
    text: "Premature optimization is the root of all evil. Programs are meant to be read by humans and only incidentally for computers to execute.",
    source: "Donald Knuth",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-dijkstra-1",
    text: "Simplicity is prerequisite for reliability. If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
    source: "Edsger Dijkstra",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-kay-1",
    text: "The best way to predict the future is to invent it. People who are really serious about software should make their own hardware.",
    source: "Alan Kay",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-brooks-1",
    text: "Adding manpower to a late software project makes it later. How does a project get to be a year late? One day at a time.",
    source: "Fred Brooks — The Mythical Man-Month",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-turing-1",
    text: "Sometimes it is the people no one imagines anything of who do the things that no one can imagine. We can only see a short distance ahead, but we can see plenty there that needs to be done.",
    source: "Alan Turing",
    category: "quote",
    difficulty: "intermediate",
  },
  {
    id: "quote-jobs-1",
    text: "Stay hungry, stay foolish. Your time is limited, so don't waste it living someone else's life.",
    source: "Steve Jobs",
    category: "quote",
    difficulty: "beginner",
  },
  {
    id: "quote-jobs-2",
    text: "Design is not just what it looks like and feels like. Design is how it works. Innovation distinguishes between a leader and a follower.",
    source: "Steve Jobs",
    category: "quote",
    difficulty: "intermediate",
  },
  // === CODE ===
  {
    id: "python-1",
    text: "def fibonacci(n):\n    if n <= 1:\n        return n\n    return fibonacci(n - 1) + fibonacci(n - 2)\n\nfor i in range(10):\n    print(fibonacci(i))",
    source: "Python — Fibonacci",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "typescript-1",
    text: "interface User {\n  name: string;\n  email: string;\n  age: number;\n}\n\nfunction greet(user: User): string {\n  return `Hello, ${user.name}!`;\n}",
    source: "TypeScript — Interfaces",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "python-2",
    text: "numbers = [1, 2, 3, 4, 5]\nsquared = [x ** 2 for x in numbers]\neven = [x for x in numbers if x % 2 == 0]",
    source: "Python — List Comprehensions",
    category: "code",
    difficulty: "beginner",
  },
  {
    id: "typescript-2",
    text: "const fetchData = async (url: string): Promise<Response> => {\n  const response = await fetch(url);\n  if (!response.ok) throw new Error('Failed');\n  return response;\n};",
    source: "TypeScript — Async/Await",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "typescript-3",
    text: "type Result<T, E = Error> = { ok: true; value: T } | { ok: false; error: E };\n\nfunction divide(a: number, b: number): Result<number> {\n  if (b === 0) return { ok: false, error: new Error('Division by zero') };\n  return { ok: true, value: a / b };\n}",
    source: "TypeScript — Result Type",
    category: "code",
    difficulty: "advanced",
  },
  {
    id: "rust-1",
    text: "fn main() {\n    let numbers = vec![1, 2, 3, 4, 5];\n    let sum: i32 = numbers.iter().sum();\n    println!(\"Sum: {}\", sum);\n}",
    source: "Rust — Vectors",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "go-1",
    text: "func main() {\n    messages := make(chan string)\n    go func() { messages <- \"ping\" }()\n    msg := <-messages\n    fmt.Println(msg)\n}",
    source: "Go — Channels",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "sql-1",
    text: "SELECT users.name, COUNT(orders.id) AS order_count\nFROM users\nLEFT JOIN orders ON users.id = orders.user_id\nGROUP BY users.name\nHAVING COUNT(orders.id) > 5\nORDER BY order_count DESC;",
    source: "SQL — Aggregation",
    category: "code",
    difficulty: "advanced",
  },
  {
    id: "python-3",
    text: "class Stack:\n    def __init__(self):\n        self.items = []\n\n    def push(self, item):\n        self.items.append(item)\n\n    def pop(self):\n        return self.items.pop()",
    source: "Python — Stack Class",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "bash-1",
    text: "#!/bin/bash\nfor file in *.txt; do\n  echo \"Processing $file\"\n  wc -l \"$file\"\ndone | sort -rn | head -5",
    source: "Bash — File Processing",
    category: "code",
    difficulty: "advanced",
  },
  {
    id: "react-1",
    text: "export default function Counter() {\n  const [count, setCount] = useState(0);\n  return (\n    <button onClick={() => setCount(c => c + 1)}>\n      Count: {count}\n    </button>\n  );\n}",
    source: "React — useState Hook",
    category: "code",
    difficulty: "intermediate",
  },
  {
    id: "css-1",
    text: ".container {\n  display: grid;\n  grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\n  gap: 1rem;\n  padding: 2rem;\n}",
    source: "CSS — Grid Layout",
    category: "code",
    difficulty: "intermediate",
  },
];

export function getRandomPassage(difficulty?: Passage["difficulty"], category?: Passage["category"]): Passage {
  let filtered = PASSAGES;
  if (difficulty) filtered = filtered.filter((p) => p.difficulty === difficulty);
  if (category) filtered = filtered.filter((p) => p.category === category);
  if (filtered.length === 0) filtered = PASSAGES;
  return filtered[Math.floor(Math.random() * filtered.length)];
}
